[package]
name = "shared_lib"
version = "0.1.0"
authors = ["Catalyst"]
edition = "2021"

[dependencies]
uint = "=0.9.1"

[dev-dependencies]
cached = "=0.40"
rand = "0.8"
itertools = "0.10"
rug = "1.17"